---
title: "Main"
author: "McCool"
date: "10/7/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r packages}
#install packages and initiate
#R collaboratory link: https://colab.research.google.com/notebook#create=true&language=r
#install.packages('tidyverse')
#install.packages('ggplot2')
#install.packages('maps')


library(maps)
library(ggplot2)
library(tidyverse)

```

``` {r scrapeData}
#make 2020 poll data
poll20 <- read_csv("https://projects.fivethirtyeight.com/polls-page/president_polls.csv")

#make 2016 results by % of vote
results16 <- read_csv("https://raw.githubusercontent.com/tonmcg/US_County_Level_Election_Results_08-16/master/2016_US_County_Level_Presidential_Results.csv")

#subsets the data we really want, including county name
sub16 <- results16 %>% filter(X1>27) %>% #Alaska county listed 28x for some reason, removes excess
  select(per_dem, per_gop, state_abbr, county_name)

#make COVID data
covfefe <- read_csv('https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv') 
print(covfefe)
```

``` {r stateData2016}
#Calculate Percent
PercentResult <- results16 %>% 
  filter(X1>27) %>%
  group_by(state_abbr) %>% 
  summarize(per_dem = sum(votes_dem)/sum(total_votes),per_gop = sum(votes_gop)/sum(total_votes))
PercentResult
```

```{r map_as_frame}
map2016 <- us_map() %>% mutate(state=abbr)
map2016 <- left_join(map2016, PercentResult16)
ggplot(data = map2016,
            mapping = aes(x = x, y = y, group = group, fill = margin)) +
  geom_polygon(color = "black")  +
  scale_fill_gradient2(low = "dark blue", mid = "white",
                                high = "dark red", breaks = c(-50, 25, 0, 25, 50)) +
  ggtitle("Electoral Victory Margin 2016") +
  theme(plot.title = element_text(hjust=0.5)) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.background = element_blank())
```
 
```{r mapping2016 victory result}

ggplot(data = map2016, mapping = aes(x = x, y = y, group = group, fill = margin >0)) +
  geom_polygon(color = "black") +
  scale_fill_manual(values = c("dark blue", "dark red"),
                      name="Winning Party",
                      labels=c("Democrat", "Republican")) +
  ggtitle("Electoral Victory Results 2016") +
  theme(plot.title = element_text(hjust=0.5)) +
  theme(panel.grid = element_blank(),
        axis.title = element_blank(),
        axis.text = element_blank(),
        axis.ticks = element_blank(),
        axis.line = element_blank(),
        panel.background = element_blank())

```
